title: Mallory Freeberg, PhD
logo: /assets/img/headshot2.jpg
description: US :us: expat living in UK :uk: | Building Communities and Collaborations | Bioinformatics & Metadata Enthusiast | Open Science Advocate | she/her
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jemoji
