title: Mallory Freeberg, PhD
logo: /assets/img/headshot2.jpg
description: Building Communities & Collaborations | Bioinformatics & Metadata Enthusiast | Open Science Advocate | US expat living in UK | she/her
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jemoji
