title: Mallory Freeberg, PhD
logo: /assets/img/2023-IMG_4201-cropped-small.jpg
description: Community & Collaboration Builder | Open Science Advocate | Human Data Sharing Expert | Bioinformatics & Metadata Enthusiast | she/her
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jemoji
