title: Mallory Freeberg, PhD
logo: /assets/img/headshot3.jpg
description: Community & Collaboration Builder | Human Data Sharing Expert | Bioinformatics & Metadata Enthusiast | Open Science Advocate | she/her
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jemoji
