title: Mallory Freeberg, PhD
logo: /assets/img/2023-IMG_4201-cropped.jpg
description: Community & Collaboration Builder | Human Data Sharing Expert | Bioinformatics & Metadata Enthusiast | Open Science Advocate | she/her
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jemoji
